export const agents = [
  {
    id: 1,
    name: "Elena Marchetti",
    speciality: "luxury residential",
    homeType: ["villas", "penthouses", "off-market"],
    image: "/images/agent_elena.jpg",
    stats: {
      yearsExperience: 12,
      sold: 84,
      rating: 4.9,
    },
    specialDetailType: "sale price",
    specialDetail: "$2.1M",
    available: true,
  },
  {
    id: 2,
    name: "James Okafor",
    speciality: "investment & commercial",
    homeType: ["commercial", "portfolio", "buy-to-let"],
    image: "/images/agent_james.jpg",
    stats: {
      yearsExperience: 9,
      closed: 116,
      rating: 4.8,
    },
    specialDetailType: "deal size",
    specialDetail: "$3.4M",
    available: true,
  },
  {
    id: 3,
    name: "Sofia Laurent",
    speciality: "new developments",
    homeType: ["off-plan", "promenade", "new build"],
    image: "/images/agent_sofia.jpg",
    stats: {
      yearsExperience: 7,
      sold: 67,
      rating: 5.0,
    },
    specialDetailType: "sale price",
    specialDetail: "1.8M",
    available: true,
  },
  {
    id: 4,
    name: "Marcus Chen",
    speciality: "rentals & relocation",
    homeType: ["rentals", "expats", "short-term"],
    image: "/images/agent_marcus.jpg",
    stats: {
      yearsExperience: 5,
      placed: 230,
      rating: 4.9,
    },
    specialDetailType: "response time",
    specialDetail: "48hr",
    available: true,
  },
  {
    id: 5,
    name: "Priya Nair",
    speciality: "international clients",
    homeType: ["international", "luxury", "riverside"],
    image: "/images/agent_priya.jpg",
    stats: {
      yearsExperience: 8,
      sold: 58,
      rating: 4.9,
    },
    specialDetailType: "sale price",
    specialDetail: "$2.9M",
    available: false,
  },
  {
    id: 6,
    name: "David Holloway",
    speciality: "investment",
    homeType: ["uptown", "buy-to-let", "off-plan"],
    image: "/images/agent_david.jpg",
    stats: {
      yearsExperience: 11,
      closed: 91,
      rating: 4.7,
    },
    specialDetailType: "above asking",
    specialDetail: "18%",
    available: true,
  },
];
