export const properties = [
  {
    id: 1,
    name: "Solaris Tower No. 41",
    featured: true,
    type: "penthouse",
    saleType: "for sale",
    location: "Riverside District",
    price: 1240000,
    bedrooms: 3,
    bathrooms: 2,
    area: 2100,
  },
  {
    id: 2,
    name: "The Verdant Suite",
    featured: true,
    type: "apartment",
    saleType: "for rent",
    location: "Uptown Heights",
    price: 4800,
    bedrooms: 2,
    bathrooms: 2,
    area: 1450,
  },
  {
    id: 3,
    name: "Amber Ridge Estate",
    featured: true,
    type: "villa",
    saleType: "for sale",
    location: "Hillcrest Gardens",
    price: 3600000,
    bedrooms: 5,
    bathrooms: 4,
    area: 5800,
  },
  {
    id: 4,
    name: "Onyx Residences",
    featured: true,
    type: "apartment",
    saleType: "new dev",
    location: "Central Promenade",
    price: 890000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
  },
  {
    id: 5,
    name: "Garden Mews Studio",
    featured: true,
    type: "studio",
    saleType: "for rent",
    location: "Westside Quarter",
    price: 2200,
    bedrooms: 0,
    bathrooms: 1,
    area: 520,
  },
  {
    id: 6,
    name: "Cedar Lane Townhouse",
    featured: true,
    type: "house",
    saleType: "for sale",
    location: "Old Harbor District",
    price: 1850000,
    bedrooms: 4,
    bathrooms: 3,
    area: 3400,
  },
];
