export const properties = [
  {
    id: 1,
    name: "Solaris Tower No. 41",
    image: "/images/penthouse.jpg",
    featured: true,
    type: "penthouse",
    saleType: "for sale",
    location: "Riverside District",
    price: 1240000,
    bedrooms: 3,
    bathrooms: 2,
    area: 2100,
    description:
      "Perched on the 41st floor of the iconic Solaris Tower, this stunning penthouse offers sweeping river views and an unmatched sense of elevation. Finished in brushed marble and warm oak, the open-plan living space flows seamlessly onto a wraparound terrace. A rare find in one of the city's most sought-after addresses.",
    details: {
      parking: 2,
      floors: 1,
      yearBuilt: 2019,
      furnished: true,
    },
  },
  {
    id: 2,
    name: "The Verdant Suite",
    image: "/images/apartment1.jpg",
    featured: true,
    type: "apartment",
    saleType: "for rent",
    location: "Uptown Heights",
    price: 4800,
    bedrooms: 2,
    bathrooms: 2,
    area: 1450,
    description:
      "A beautifully appointed apartment nestled in the leafy calm of Uptown Heights. Floor-to-ceiling windows flood every room with natural light, while the curated interiors strike a balance between comfort and sophistication. Ideal for professionals or couples seeking a refined urban retreat.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 2021,
      furnished: true,
    },
  },
  {
    id: 3,
    name: "Amber Ridge Estate",
    image: "/images/villa.jpg",
    featured: true,
    type: "villa",
    saleType: "for sale",
    location: "Hillcrest Gardens",
    price: 3600000,
    bedrooms: 5,
    bathrooms: 4,
    area: 5800,
    description:
      "Set within manicured grounds atop Hillcrest Gardens, Amber Ridge Estate is a landmark residence that commands panoramic views of the valley below. The home features five generous bedroom suites, a chef's kitchen, a private pool, and a separate guest cottage — all finished to an exceptional standard.",
    details: {
      parking: 4,
      floors: 2,
      yearBuilt: 2016,
      furnished: false,
    },
  },
  {
    id: 4,
    name: "Onyx Residences",
    image: "/images/apartment2.jpg",
    featured: true,
    type: "apartment",
    saleType: "new dev",
    location: "Central Promenade",
    price: 890000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    description:
      "Part of a landmark new development on the Central Promenade, Onyx Residences sets a new benchmark for city living. Each unit is designed with clean architectural lines, premium fittings, and smart home integration. Residents enjoy access to a rooftop lounge, concierge service, and a fully equipped fitness center.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 2024,
      furnished: false,
    },
  },
  {
    id: 5,
    name: "Garden Mews Studio",
    image: "/images/studio.jpg",
    featured: true,
    type: "studio",
    saleType: "for rent",
    location: "Westside Quarter",
    price: 2200,
    bedrooms: 0,
    bathrooms: 1,
    area: 520,
    description:
      "Tucked into a quiet mews lane in the heart of Westside Quarter, this charming studio is a compact yet carefully designed space. High ceilings, exposed brick, and a private courtyard garden give it a warmth rarely found at this price point. Perfect for a single professional or creative looking for character over cookie-cutter.",
    details: {
      parking: 0,
      floors: 1,
      yearBuilt: 2010,
      furnished: true,
    },
  },
  {
    id: 6,
    name: "Cedar Lane Townhouse",
    image: "/images/house.jpg",
    featured: true,
    type: "house",
    saleType: "for sale",
    location: "Old Harbor District",
    price: 1850000,
    bedrooms: 4,
    bathrooms: 3,
    area: 3400,
    description:
      "An elegant Victorian-era townhouse sympathetically restored for modern living. Spanning four floors on one of Old Harbor's most picturesque streets, Cedar Lane offers generous family accommodation with original period features sitting alongside contemporary finishes. A private rear garden and a double garage complete this exceptional offering.",
    details: {
      parking: 2,
      floors: 4,
      yearBuilt: 1898,
      furnished: false,
    },
  },
  {
    id: 7,
    name: "The Halcyon",
    image: "/images/apartment3.jpg",
    featured: false,
    type: "apartment",
    saleType: "for sale",
    location: "Central Promenade",
    price: 720000,
    bedrooms: 2,
    bathrooms: 1,
    area: 1050,
    description:
      "A polished city apartment with an understated elegance. The Halcyon sits mid-floor in one of the Promenade's finest residential buildings, offering residents both tranquility and connectivity. The interiors are finished in neutral tones with warm accent lighting throughout.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 2020,
      furnished: false,
    },
  },
  {
    id: 8,
    name: "Ironwood House",
    image: "/images/house2.jpg",
    featured: false,
    type: "house",
    saleType: "for sale",
    location: "Hillcrest Gardens",
    price: 2100000,
    bedrooms: 4,
    bathrooms: 3,
    area: 3900,
    description:
      "A bold, architect-designed home built around a central courtyard that floods every room with natural light. Ironwood House is a statement of modern residential design — raw concrete textures balanced by warm timber accents and lush landscaping.",
    details: {
      parking: 2,
      floors: 2,
      yearBuilt: 2022,
      furnished: false,
    },
  },
  {
    id: 9,
    name: "Marble Lane Studio",
    image: "/images/studio2.jpg",
    featured: false,
    type: "studio",
    saleType: "for rent",
    location: "Central Promenade",
    price: 2800,
    bedrooms: 0,
    bathrooms: 1,
    area: 480,
    description:
      "A sleek, well-proportioned studio in one of the city's most vibrant corridors. Recently refurbished with Italian marble finishes and integrated appliances, Marble Lane is ideal for someone who wants everything at arm's reach.",
    details: {
      parking: 0,
      floors: 1,
      yearBuilt: 2018,
      furnished: true,
    },
  },
  {
    id: 10,
    name: "The Crestview",
    image: "/images/penthouse2.jpg",
    featured: false,
    type: "penthouse",
    saleType: "for sale",
    location: "Uptown Heights",
    price: 2950000,
    bedrooms: 4,
    bathrooms: 3,
    area: 3800,
    description:
      "The Crestview occupies the entire top floor of one of Uptown Heights' most recognisable towers. A private lift, double-height ceilings, and a wraparound terrace with unobstructed skyline views make this one of the most coveted residences in the city.",
    details: {
      parking: 2,
      floors: 1,
      yearBuilt: 2021,
      furnished: false,
    },
  },
  {
    id: 11,
    name: "Sage & Stone Villa",
    image: "/images/villa2.jpg",
    featured: false,
    type: "villa",
    saleType: "for sale",
    location: "Hillcrest Gardens",
    price: 4200000,
    bedrooms: 6,
    bathrooms: 5,
    area: 6800,
    description:
      "One of the largest private residences in Hillcrest Gardens, Sage & Stone Villa is a masterwork of luxury living. The property sits on over half an acre, with a full-size tennis court, heated pool, wine cellar, and a six-car garage.",
    details: {
      parking: 6,
      floors: 2,
      yearBuilt: 2014,
      furnished: false,
    },
  },
  {
    id: 12,
    name: "The Ember Flat",
    image: "/images/apartment4.jpg",
    featured: false,
    type: "apartment",
    saleType: "for rent",
    location: "Westside Quarter",
    price: 3600,
    bedrooms: 1,
    bathrooms: 1,
    area: 780,
    description:
      "Warm, inviting, and thoughtfully laid out, The Ember Flat is a one-bedroom apartment bathed in afternoon light. The open kitchen and living area make the most of every square foot, and the building offers a communal rooftop garden for residents.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 2017,
      furnished: true,
    },
  },
  {
    id: 13,
    name: "Bayside Loft",
    image: "/images/apartment5.jpg",
    featured: false,
    type: "apartment",
    saleType: "for sale",
    location: "Old Harbor District",
    price: 980000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1600,
    description:
      "A converted warehouse loft retaining original industrial features — exposed steel beams, polished concrete floors, and oversized factory windows. Bayside Loft is a rare breed: a home with genuine character in one of the city's most storied neighborhoods.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 1965,
      furnished: false,
    },
  },
  {
    id: 14,
    name: "Northgate Terrace",
    image: "/images/house3.jpg",
    featured: false,
    type: "house",
    saleType: "for sale",
    location: "Riverside District",
    price: 1420000,
    bedrooms: 3,
    bathrooms: 2,
    area: 2600,
    description:
      "A handsome mid-century terrace home with a generous rear garden and a recently extended open-plan ground floor. Northgate Terrace sits on a quiet, tree-lined street moments from the riverfront and a strong selection of local schools.",
    details: {
      parking: 1,
      floors: 2,
      yearBuilt: 1958,
      furnished: false,
    },
  },
  {
    id: 15,
    name: "Lune Studio",
    image: "/images/studio3.jpg",
    featured: false,
    type: "studio",
    saleType: "for rent",
    location: "Uptown Heights",
    price: 1950,
    bedrooms: 0,
    bathrooms: 1,
    area: 440,
    description:
      "A compact, moon-lit studio with soft minimalist interiors on the sixth floor of a boutique Uptown building. Large windows draw in the city skyline, and the building features a 24-hour concierge and on-site laundry facilities.",
    details: {
      parking: 0,
      floors: 1,
      yearBuilt: 2019,
      furnished: true,
    },
  },
  {
    id: 16,
    name: "The Greystone",
    image: "/images/apartment6.jpg",
    featured: false,
    type: "apartment",
    saleType: "new dev",
    location: "Riverside District",
    price: 650000,
    bedrooms: 1,
    bathrooms: 1,
    area: 870,
    description:
      "Part of a refined new riverside development, The Greystone collection offers one and two-bedroom apartments with private balconies and river-facing views. Each unit is specification-built with underfloor heating, integrated appliances, and video entry.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 2024,
      furnished: false,
    },
  },
  {
    id: 17,
    name: "Copperwood Cottage",
    image: "/images/house4.jpg",
    featured: false,
    type: "house",
    saleType: "for sale",
    location: "Hillcrest Gardens",
    price: 870000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1850,
    description:
      "A charming detached cottage set behind a mature copper beech hedge, giving it a sense of seclusion rare this close to the city. The interiors are cosy yet contemporary, with a log-burning fireplace as the centrepiece of the sitting room.",
    details: {
      parking: 2,
      floors: 2,
      yearBuilt: 1934,
      furnished: false,
    },
  },
  {
    id: 18,
    name: "Zephyr Apartments No. 8",
    image: "/images/apartment7.jpg",
    featured: false,
    type: "apartment",
    saleType: "for rent",
    location: "Central Promenade",
    price: 5200,
    bedrooms: 3,
    bathrooms: 2,
    area: 1750,
    description:
      "A spacious three-bedroom apartment in one of the Promenade's most prestigious residential blocks. Zephyr No. 8 features a large private terrace, a chef-spec kitchen, and access to a residents-only pool and spa.",
    details: {
      parking: 2,
      floors: 1,
      yearBuilt: 2020,
      furnished: true,
    },
  },
  {
    id: 19,
    name: "Vault Loft",
    image: "/images/apartment8.jpg",
    featured: false,
    type: "apartment",
    saleType: "for sale",
    location: "Old Harbor District",
    price: 1150000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1900,
    description:
      "Originally a 19th-century bank vault, this extraordinary loft conversion marries heritage architecture with avant-garde interiors. Soaring arched ceilings, original vault doors repurposed as feature walls, and bespoke steel staircases make Vault Loft truly one of a kind.",
    details: {
      parking: 1,
      floors: 2,
      yearBuilt: 1882,
      furnished: false,
    },
  },
  {
    id: 20,
    name: "Palm Court Penthouse",
    image: "/images/penthouse3.jpg",
    featured: false,
    type: "penthouse",
    saleType: "for sale",
    location: "Westside Quarter",
    price: 1980000,
    bedrooms: 3,
    bathrooms: 3,
    area: 2900,
    description:
      "A sun-drenched penthouse with a landscaped rooftop terrace featuring mature palms and a private plunge pool. Palm Court blends resort-style living with urban sophistication — a rare combination at this address.",
    details: {
      parking: 2,
      floors: 1,
      yearBuilt: 2018,
      furnished: false,
    },
  },
  {
    id: 21,
    name: "Birch & Bay House",
    image: "/images/house5.jpg",
    featured: false,
    type: "house",
    saleType: "for sale",
    location: "Old Harbor District",
    price: 2350000,
    bedrooms: 5,
    bathrooms: 4,
    area: 4200,
    description:
      "A sprawling family home with direct water access and a private jetty. Birch & Bay House features an open-plan kitchen and living area that opens onto a wide timber deck overlooking the harbor — an entertainer's dream.",
    details: {
      parking: 3,
      floors: 2,
      yearBuilt: 2005,
      furnished: false,
    },
  },
  {
    id: 22,
    name: "The Foxglove",
    image: "/images/apartment9.jpg",
    featured: false,
    type: "apartment",
    saleType: "for rent",
    location: "Hillcrest Gardens",
    price: 3100,
    bedrooms: 2,
    bathrooms: 1,
    area: 1100,
    description:
      "A light-filled garden-facing apartment surrounded by the greenery of Hillcrest. The Foxglove offers a peaceful retreat from city noise, with large sash windows, high ceilings, and a private balcony overlooking manicured communal gardens.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 2013,
      furnished: false,
    },
  },
  {
    id: 23,
    name: "Dune House",
    image: "/images/villa3.jpg",
    featured: false,
    type: "villa",
    saleType: "for sale",
    location: "Riverside District",
    price: 5100000,
    bedrooms: 7,
    bathrooms: 6,
    area: 8200,
    description:
      "A monumental riverside villa with an imposing facade and equally impressive interiors. Dune House spans over 8,000 square feet across three floors, with a cinema room, gym, indoor pool, and staff quarters. The grounds extend to two acres with a formal garden.",
    details: {
      parking: 6,
      floors: 3,
      yearBuilt: 2011,
      furnished: false,
    },
  },
  {
    id: 24,
    name: "Studio Eleven",
    image: "/images/studio4.jpg",
    featured: false,
    type: "studio",
    saleType: "for rent",
    location: "Old Harbor District",
    price: 1800,
    bedrooms: 0,
    bathrooms: 1,
    area: 395,
    description:
      "A well-priced harbor-side studio with views of the working docks and an industrial-chic aesthetic. Studio Eleven is a popular choice among artists and writers drawn to the area's creative energy and historic character.",
    details: {
      parking: 0,
      floors: 1,
      yearBuilt: 2009,
      furnished: true,
    },
  },
  {
    id: 25,
    name: "Helix Tower Suite 22",
    image: "/images/apartment10.jpg",
    featured: false,
    type: "apartment",
    saleType: "new dev",
    location: "Central Promenade",
    price: 1050000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1350,
    description:
      "Part of the landmark Helix Tower development, Suite 22 offers a premium two-bedroom layout with floor-to-ceiling glass, a private sky terrace, and access to world-class resident amenities including a sky bar, co-working lounge, and indoor pool.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 2025,
      furnished: false,
    },
  },
  {
    id: 26,
    name: "The Rosewood Flat",
    image: "/images/apartment11.jpg",
    featured: false,
    type: "apartment",
    saleType: "for sale",
    location: "Westside Quarter",
    price: 540000,
    bedrooms: 1,
    bathrooms: 1,
    area: 720,
    description:
      "A beautifully maintained first-floor flat in a period mansion block. The Rosewood Flat retains original cornicing and fireplaces while offering a modern kitchen and bathroom. A calm, tree-canopied street ensures peace even in this central location.",
    details: {
      parking: 0,
      floors: 1,
      yearBuilt: 1905,
      furnished: false,
    },
  },
  {
    id: 27,
    name: "Indigo Mews No. 3",
    image: "/images/house6.jpg",
    featured: false,
    type: "house",
    saleType: "for sale",
    location: "Uptown Heights",
    price: 1680000,
    bedrooms: 3,
    bathrooms: 2,
    area: 2400,
    description:
      "A contemporary mews house finished to an exceptional standard. Indigo Mews No. 3 features a rooftop terrace with outdoor kitchen, a double-height living space, and a private garage with an electric vehicle charging point.",
    details: {
      parking: 1,
      floors: 3,
      yearBuilt: 2023,
      furnished: false,
    },
  },
  {
    id: 28,
    name: "The Mineral Suite",
    image: "/images/apartment12.jpg",
    featured: false,
    type: "apartment",
    saleType: "for rent",
    location: "Riverside District",
    price: 4200,
    bedrooms: 2,
    bathrooms: 2,
    area: 1300,
    description:
      "An interior designer's own apartment, available to rent for the first time. The Mineral Suite is layered with texture — travertine, linen, aged brass — creating a home that feels curated over decades rather than dressed overnight.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 2017,
      furnished: true,
    },
  },
  {
    id: 29,
    name: "Highbury Villa",
    image: "/images/villa4.jpg",
    featured: false,
    type: "villa",
    saleType: "for sale",
    location: "Uptown Heights",
    price: 3850000,
    bedrooms: 5,
    bathrooms: 5,
    area: 6200,
    description:
      "An Uptown classic — a double-fronted detached villa sitting behind electric gates on one of the area's finest private roads. Highbury Villa combines stately proportions with a warm, liveable interior across three expansive floors.",
    details: {
      parking: 4,
      floors: 3,
      yearBuilt: 2007,
      furnished: false,
    },
  },
  {
    id: 30,
    name: "Canal View Studio",
    image: "/images/studio5.jpg",
    featured: false,
    type: "studio",
    saleType: "for rent",
    location: "Westside Quarter",
    price: 2050,
    bedrooms: 0,
    bathrooms: 1,
    area: 510,
    description:
      "A charming waterside studio with direct canal views from a Juliet balcony. Canal View Studio is freshly refurbished with Scandi-inspired interiors and is located moments from the Quarter's thriving café and gallery scene.",
    details: {
      parking: 0,
      floors: 1,
      yearBuilt: 2015,
      furnished: true,
    },
  },
  {
    id: 31,
    name: "Topaz Residences No. 7",
    image: "/images/apartment13.jpg",
    featured: false,
    type: "apartment",
    saleType: "new dev",
    location: "Hillcrest Gardens",
    price: 760000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    description:
      "Newly completed and ready to move into, Topaz No. 7 is a well-specified two-bedroom apartment in a boutique eight-unit development. The building features a private residents' garden and dedicated cycle storage.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 2024,
      furnished: false,
    },
  },
  {
    id: 32,
    name: "The Ashford",
    image: "/images/penthouse4.jpg",
    featured: false,
    type: "penthouse",
    saleType: "for sale",
    location: "Old Harbor District",
    price: 2250000,
    bedrooms: 3,
    bathrooms: 3,
    area: 3100,
    description:
      "The crown of a beautifully restored Victorian warehouse, The Ashford penthouse spans the entire top floor with a dramatic double-height living room and a terrace overlooking the harbor's historic waterfront.",
    details: {
      parking: 2,
      floors: 2,
      yearBuilt: 1890,
      furnished: false,
    },
  },
  {
    id: 33,
    name: "Fieldstone Manor",
    image: "/images/villa5.jpg",
    featured: false,
    type: "villa",
    saleType: "for sale",
    location: "Hillcrest Gardens",
    price: 6800000,
    bedrooms: 8,
    bathrooms: 7,
    area: 10500,
    description:
      "One of the most significant private residences to come to market in a decade. Fieldstone Manor is a grand estate set in four acres of formal gardens, featuring a ballroom, a billiards room, a full staff wing, and a heated outdoor swimming pool.",
    details: {
      parking: 8,
      floors: 3,
      yearBuilt: 1928,
      furnished: false,
    },
  },
  {
    id: 34,
    name: "The Pebble Studio",
    image: "/images/studio6.jpg",
    featured: false,
    type: "studio",
    saleType: "for sale",
    location: "Riverside District",
    price: 320000,
    bedrooms: 0,
    bathrooms: 1,
    area: 460,
    description:
      "An affordable riverside entry point. The Pebble Studio is a compact but well-thought-out space with a riverside outlook, making it an excellent first purchase or buy-to-let investment.",
    details: {
      parking: 0,
      floors: 1,
      yearBuilt: 2012,
      furnished: false,
    },
  },
  {
    id: 35,
    name: "Waverly House",
    image: "/images/house7.jpg",
    featured: false,
    type: "house",
    saleType: "for sale",
    location: "Westside Quarter",
    price: 1200000,
    bedrooms: 4,
    bathrooms: 3,
    area: 2900,
    description:
      "A wide-fronted detached family home at the quieter end of Westside's residential streets. Waverly House has been extended to the rear creating a spectacular kitchen and family room that opens onto a south-facing garden.",
    details: {
      parking: 2,
      floors: 2,
      yearBuilt: 1976,
      furnished: false,
    },
  },
  {
    id: 36,
    name: "Azure Skies Apartment",
    image: "/images/apartment14.jpg",
    featured: false,
    type: "apartment",
    saleType: "for rent",
    location: "Central Promenade",
    price: 6100,
    bedrooms: 3,
    bathrooms: 2,
    area: 2000,
    description:
      "A high-floor apartment with uninterrupted sky views from every room. Azure Skies is fully furnished to hotel standard and available on flexible lease terms — a favourite among senior executives and diplomats.",
    details: {
      parking: 2,
      floors: 1,
      yearBuilt: 2022,
      furnished: true,
    },
  },
  {
    id: 37,
    name: "The Foundry",
    image: "/images/apartment15.jpg",
    featured: false,
    type: "apartment",
    saleType: "for sale",
    location: "Old Harbor District",
    price: 875000,
    bedrooms: 2,
    bathrooms: 1,
    area: 1400,
    description:
      "A raw, honest conversion of an old iron foundry. The Foundry apartment retains the patina of its industrial past while offering all the comforts of contemporary living — underfloor heating, a modern kitchen, and a mezzanine sleeping level.",
    details: {
      parking: 1,
      floors: 2,
      yearBuilt: 1902,
      furnished: false,
    },
  },
  {
    id: 38,
    name: "Clover Hill Cottage",
    image: "/images/house8.jpg",
    featured: false,
    type: "house",
    saleType: "for sale",
    location: "Hillcrest Gardens",
    price: 950000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1950,
    description:
      "A picture-perfect stone cottage with a thatched garden pergola and a spring-fed fish pond. Clover Hill has been renovated with painstaking attention to detail, blending rural character with understated luxury finishes.",
    details: {
      parking: 2,
      floors: 2,
      yearBuilt: 1912,
      furnished: false,
    },
  },
  {
    id: 39,
    name: "Zenith Studio Tower",
    image: "/images/studio7.jpg",
    featured: false,
    type: "studio",
    saleType: "for rent",
    location: "Central Promenade",
    price: 3200,
    bedrooms: 0,
    bathrooms: 1,
    area: 560,
    description:
      "A premium studio on the 28th floor of the Zenith Tower, offering cinema-quality city views in a compact, smartly designed layout. The building features co-working spaces, a sky pool, and 24-hour concierge.",
    details: {
      parking: 0,
      floors: 1,
      yearBuilt: 2023,
      furnished: true,
    },
  },
  {
    id: 40,
    name: "The Ivory",
    image: "/images/penthouse5.jpg",
    featured: false,
    type: "penthouse",
    saleType: "for sale",
    location: "Central Promenade",
    price: 4750000,
    bedrooms: 5,
    bathrooms: 4,
    area: 5200,
    description:
      "Pure, luminous, and breathtaking. The Ivory is a duplex penthouse clad entirely in white Calacatta marble, with a 270-degree terrace and a private lift lobby. The finest penthouse currently available on the Promenade.",
    details: {
      parking: 3,
      floors: 2,
      yearBuilt: 2023,
      furnished: false,
    },
  },
  {
    id: 41,
    name: "Sandalwood Apartments No. 4",
    image: "/images/apartment16.jpg",
    featured: false,
    type: "apartment",
    saleType: "for sale",
    location: "Uptown Heights",
    price: 615000,
    bedrooms: 1,
    bathrooms: 1,
    area: 820,
    description:
      "A calm, well-proportioned one-bedroom apartment in a boutique Uptown block. Sandalwood No. 4 offers quiet tree-lined views, a private balcony, and underground parking in one of the city's most walkable residential pockets.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 2016,
      furnished: false,
    },
  },
  {
    id: 42,
    name: "Meridian House",
    image: "/images/house9.jpg",
    featured: false,
    type: "house",
    saleType: "for sale",
    location: "Riverside District",
    price: 1750000,
    bedrooms: 4,
    bathrooms: 3,
    area: 3200,
    description:
      "A confident, well-built family home steps from the riverfront. Meridian House is notable for its unusually large corner plot, giving the rear garden a size rarely found this close to the city center.",
    details: {
      parking: 2,
      floors: 2,
      yearBuilt: 1999,
      furnished: false,
    },
  },
  {
    id: 43,
    name: "Slate & Oak Studio",
    image: "/images/studio8.jpg",
    featured: false,
    type: "studio",
    saleType: "for rent",
    location: "Hillcrest Gardens",
    price: 1700,
    bedrooms: 0,
    bathrooms: 1,
    area: 420,
    description:
      "A ground-floor garden studio finished with slate tile flooring and oak joinery throughout. Slate & Oak is a peaceful retreat with its own private entrance and a small patio garden — perfect for a couple or solo occupant.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 2014,
      furnished: true,
    },
  },
  {
    id: 44,
    name: "Harbour Gate Residences",
    image: "/images/apartment17.jpg",
    featured: false,
    type: "apartment",
    saleType: "new dev",
    location: "Old Harbor District",
    price: 920000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1280,
    description:
      "A new waterfront development occupying the site of the city's original harbour gate. Each residence offers framed harbour views, private balconies, and access to a residents' club with a gym, spa, and private dining room.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 2025,
      furnished: false,
    },
  },
  {
    id: 45,
    name: "The Obsidian",
    image: "/images/apartment18.jpg",
    featured: false,
    type: "apartment",
    saleType: "for rent",
    location: "Uptown Heights",
    price: 4500,
    bedrooms: 2,
    bathrooms: 2,
    area: 1550,
    description:
      "Dark, dramatic, and deeply considered. The Obsidian apartment is finished in charcoal stone and dark timber with brass fixtures throughout — a moody, sophisticated space for those who like their home to make a statement.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 2021,
      furnished: true,
    },
  },
  {
    id: 46,
    name: "Pinecrest House",
    image: "/images/house10.jpg",
    featured: false,
    type: "house",
    saleType: "for sale",
    location: "Hillcrest Gardens",
    price: 2800000,
    bedrooms: 5,
    bathrooms: 4,
    area: 4800,
    description:
      "A stately home wrapped in Virginia creeper at the crown of Hillcrest's most private cul-de-sac. Pinecrest offers five generous bedrooms, a wine cellar, a home office suite, and a landscaped garden with a heated pool.",
    details: {
      parking: 3,
      floors: 3,
      yearBuilt: 2001,
      furnished: false,
    },
  },
  {
    id: 47,
    name: "Terracotta Heights",
    image: "/images/apartment19.jpg",
    featured: false,
    type: "apartment",
    saleType: "for sale",
    location: "Westside Quarter",
    price: 480000,
    bedrooms: 1,
    bathrooms: 1,
    area: 690,
    description:
      "A sun-warmed apartment on the upper floors of a terracotta-tiled Westside block. Compact, characterful, and affordable — an ideal entry-level purchase or low-maintenance investment in a rapidly gentrifying pocket.",
    details: {
      parking: 0,
      floors: 1,
      yearBuilt: 2008,
      furnished: false,
    },
  },
  {
    id: 48,
    name: "The Willow Mews",
    image: "/images/house11.jpg",
    featured: false,
    type: "house",
    saleType: "for sale",
    location: "Uptown Heights",
    price: 1950000,
    bedrooms: 3,
    bathrooms: 3,
    area: 2700,
    description:
      "A sleek mews house tucked behind Uptown's grandest terrace. The Willow Mews has been rebuilt from the ground up with a glazed rear extension, a bespoke staircase, and a rooftop terrace with a pergola and outdoor fireplace.",
    details: {
      parking: 1,
      floors: 3,
      yearBuilt: 2022,
      furnished: false,
    },
  },
  {
    id: 49,
    name: "Studio Blanc",
    image: "/images/studio9.jpg",
    featured: false,
    type: "studio",
    saleType: "for sale",
    location: "Central Promenade",
    price: 390000,
    bedrooms: 0,
    bathrooms: 1,
    area: 495,
    description:
      "An all-white studio apartment with a minimalist ethos and maximum natural light. Studio Blanc is a study in restraint — high ceilings, a clear layout, and a south-facing window seat that is hard to leave.",
    details: {
      parking: 0,
      floors: 1,
      yearBuilt: 2020,
      furnished: true,
    },
  },
  {
    id: 50,
    name: "Cobalt Sky Penthouse",
    image: "/images/penthouse6.jpg",
    featured: false,
    type: "penthouse",
    saleType: "for sale",
    location: "Riverside District",
    price: 3300000,
    bedrooms: 4,
    bathrooms: 3,
    area: 4100,
    description:
      "A statement penthouse defined by its cobalt-tinted glazed roofline and panoramic river outlook. The living space is anchored by a custom fireplace and opens onto two terraces — one facing east for morning sun, one west for evening views.",
    details: {
      parking: 2,
      floors: 2,
      yearBuilt: 2020,
      furnished: false,
    },
  },
  {
    id: 51,
    name: "Ferngrove Apartment",
    image: "/images/apartment20.jpg",
    featured: false,
    type: "apartment",
    saleType: "for rent",
    location: "Hillcrest Gardens",
    price: 2900,
    bedrooms: 2,
    bathrooms: 1,
    area: 1050,
    description:
      "A comfortable and quietly elegant two-bedroom apartment backing onto a wooded hillside. Ferngrove has a cosy feel enhanced by wooden floors, bay windows, and a cast-iron radiator that rumbles satisfyingly in winter.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 2011,
      furnished: false,
    },
  },
  {
    id: 52,
    name: "Harbourside Villa",
    image: "/images/villa6.jpg",
    featured: false,
    type: "villa",
    saleType: "for sale",
    location: "Old Harbor District",
    price: 7200000,
    bedrooms: 7,
    bathrooms: 6,
    area: 9600,
    description:
      "The most prestigious residential address in the Old Harbor District. Harbourside Villa sits on a private peninsula with water on three sides, offering unrivalled privacy and views. A once-in-a-generation opportunity.",
    details: {
      parking: 6,
      floors: 3,
      yearBuilt: 2008,
      furnished: false,
    },
  },
  {
    id: 53,
    name: "Burnished Oak House",
    image: "/images/house12.jpg",
    featured: false,
    type: "house",
    saleType: "for sale",
    location: "Westside Quarter",
    price: 1380000,
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    description:
      "A handsome Edwardian semi-detached house with original oak floorboards throughout and a beautifully planted rear garden. Burnished Oak has been sensitively extended and modernised without losing any of its period warmth.",
    details: {
      parking: 1,
      floors: 2,
      yearBuilt: 1908,
      furnished: false,
    },
  },
  {
    id: 54,
    name: "Eclipse Apartments No. 12",
    image: "/images/apartment21.jpg",
    featured: false,
    type: "apartment",
    saleType: "new dev",
    location: "Uptown Heights",
    price: 1180000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1650,
    description:
      "The final release in the award-winning Eclipse development. No. 12 is a corner three-bedroom apartment with dual-aspect views, a large wraparound balcony, and premium specification throughout.",
    details: {
      parking: 2,
      floors: 1,
      yearBuilt: 2024,
      furnished: false,
    },
  },
  {
    id: 55,
    name: "The Tangerine Studio",
    image: "/images/studio10.jpg",
    featured: false,
    type: "studio",
    saleType: "for rent",
    location: "Riverside District",
    price: 2400,
    bedrooms: 0,
    bathrooms: 1,
    area: 530,
    description:
      "A bold, colour-forward studio with terracotta-plastered walls and rattan furnishings. The Tangerine is a furnished let with instant livability — move in on a Monday and feel at home by Tuesday.",
    details: {
      parking: 0,
      floors: 1,
      yearBuilt: 2016,
      furnished: true,
    },
  },
  {
    id: 56,
    name: "Blackwood Penthouse",
    image: "/images/penthouse7.jpg",
    featured: false,
    type: "penthouse",
    saleType: "for rent",
    location: "Central Promenade",
    price: 18000,
    bedrooms: 4,
    bathrooms: 4,
    area: 4600,
    description:
      "Available to rent for the first time, Blackwood Penthouse is among the city's most coveted private residences. A private cinema, wine vault, gym, and a 360-degree rooftop terrace are among the highlights of this remarkable property.",
    details: {
      parking: 3,
      floors: 2,
      yearBuilt: 2021,
      furnished: true,
    },
  },
  {
    id: 57,
    name: "Quartz Corner House",
    image: "/images/house13.jpg",
    featured: false,
    type: "house",
    saleType: "for sale",
    location: "Central Promenade",
    price: 3100000,
    bedrooms: 5,
    bathrooms: 4,
    area: 4400,
    description:
      "A commanding corner townhouse on the Promenade's most photographed street. Quartz Corner House combines grand proportions with a warm family home layout — a rare combination on this prestigious address.",
    details: {
      parking: 2,
      floors: 4,
      yearBuilt: 1888,
      furnished: false,
    },
  },
  {
    id: 58,
    name: "The Lantern Flat",
    image: "/images/apartment22.jpg",
    featured: false,
    type: "apartment",
    saleType: "for sale",
    location: "Old Harbor District",
    price: 430000,
    bedrooms: 1,
    bathrooms: 1,
    area: 640,
    description:
      "A charming first-floor flat named for the original harbour lantern that hangs outside its entrance. The Lantern Flat is compact, characterful, and excellently located for both the harbor and the city center.",
    details: {
      parking: 0,
      floors: 1,
      yearBuilt: 1955,
      furnished: false,
    },
  },
  {
    id: 59,
    name: "Sienna Villa",
    image: "/images/villa7.jpg",
    featured: false,
    type: "villa",
    saleType: "for sale",
    location: "Westside Quarter",
    price: 2900000,
    bedrooms: 5,
    bathrooms: 4,
    area: 5500,
    description:
      "A Tuscan-inspired villa brought to life on Westside's quietest road. Sienna Villa features terracotta roof tiles, a central courtyard with a loggia, and an olive grove garden — an unlikely and extraordinary find in the city.",
    details: {
      parking: 4,
      floors: 2,
      yearBuilt: 2003,
      furnished: false,
    },
  },
  {
    id: 60,
    name: "The Northern Light",
    image: "/images/apartment23.jpg",
    featured: false,
    type: "apartment",
    saleType: "for rent",
    location: "Riverside District",
    price: 3800,
    bedrooms: 2,
    bathrooms: 1,
    area: 1200,
    description:
      "A Scandinavian-influenced apartment with natural pine furniture, white walls, and a wood-burning stove. The Northern Light is a rare warm and homely rental in a city full of cold show apartments.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 2018,
      furnished: true,
    },
  },
  {
    id: 61,
    name: "Goldenrod House",
    image: "/images/house14.jpg",
    featured: false,
    type: "house",
    saleType: "for sale",
    location: "Uptown Heights",
    price: 2400000,
    bedrooms: 5,
    bathrooms: 4,
    area: 4100,
    description:
      "A golden-brick detached house with a rear garden that backs directly onto Uptown Park. Goldenrod House is a cherished family home with a large kitchen-diner, a playroom, a home office, and a self-contained annexe.",
    details: {
      parking: 2,
      floors: 3,
      yearBuilt: 1994,
      furnished: false,
    },
  },
  {
    id: 62,
    name: "The Plinth Studio",
    image: "/images/studio11.jpg",
    featured: false,
    type: "studio",
    saleType: "for sale",
    location: "Uptown Heights",
    price: 355000,
    bedrooms: 0,
    bathrooms: 1,
    area: 475,
    description:
      "A collector's studio apartment in a converted arts building. The Plinth features concrete ceilings, gallery-style white walls, and industrial pendant lighting — a space that feels like living in a private art gallery.",
    details: {
      parking: 0,
      floors: 1,
      yearBuilt: 2006,
      furnished: false,
    },
  },
  {
    id: 63,
    name: "Lakewood Residences No. 9",
    image: "/images/apartment24.jpg",
    featured: false,
    type: "apartment",
    saleType: "new dev",
    location: "Hillcrest Gardens",
    price: 840000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1180,
    description:
      "Overlooking a new landscaped lake at the heart of the Lakewood masterplan, No. 9 is a generously proportioned two-bedroom apartment with a terrace designed for outdoor dining. The development includes a gym, yoga studio, and concierge.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 2025,
      furnished: false,
    },
  },
  {
    id: 64,
    name: "The Driftwood",
    image: "/images/house15.jpg",
    featured: false,
    type: "house",
    saleType: "for sale",
    location: "Old Harbor District",
    price: 1650000,
    bedrooms: 3,
    bathrooms: 2,
    area: 2500,
    description:
      "A nautically influenced harbor house with a ship-lap exterior and an interior filled with natural light and salvaged maritime materials. The Driftwood is a unique property for a buyer who values character above all else.",
    details: {
      parking: 1,
      floors: 2,
      yearBuilt: 1978,
      furnished: false,
    },
  },
  {
    id: 65,
    name: "The Silver Apartment",
    image: "/images/apartment25.jpg",
    featured: false,
    type: "apartment",
    saleType: "for rent",
    location: "Central Promenade",
    price: 7400,
    bedrooms: 4,
    bathrooms: 3,
    area: 2400,
    description:
      "A full-floor apartment on one of the Promenade's most exclusive residential towers. The Silver features four double bedrooms, a formal dining room, a fully staffed lobby, and a private parking bay.",
    details: {
      parking: 2,
      floors: 1,
      yearBuilt: 2019,
      furnished: true,
    },
  },
  {
    id: 66,
    name: "Mortar & Stone Villa",
    image: "/images/villa8.jpg",
    featured: false,
    type: "villa",
    saleType: "for sale",
    location: "Riverside District",
    price: 4600000,
    bedrooms: 6,
    bathrooms: 5,
    area: 7400,
    description:
      "A raw, elemental villa constructed entirely from reclaimed stone and steel. Mortar & Stone is the vision of an award-winning architect and stands as one of the most distinctive private homes in the city.",
    details: {
      parking: 4,
      floors: 2,
      yearBuilt: 2017,
      furnished: false,
    },
  },
  {
    id: 67,
    name: "Sunrise Mews House",
    image: "/images/house16.jpg",
    featured: false,
    type: "house",
    saleType: "for sale",
    location: "Westside Quarter",
    price: 1100000,
    bedrooms: 3,
    bathrooms: 2,
    area: 2100,
    description:
      "A cheerful east-facing mews house that catches the first light every morning. Sunrise Mews is a well-loved home in a quiet cobbled lane, with a courtyard garden and a converted garage currently used as a home studio.",
    details: {
      parking: 1,
      floors: 2,
      yearBuilt: 1989,
      furnished: false,
    },
  },
  {
    id: 68,
    name: "Ash & Linen Studio",
    image: "/images/studio12.jpg",
    featured: false,
    type: "studio",
    saleType: "for rent",
    location: "Uptown Heights",
    price: 2300,
    bedrooms: 0,
    bathrooms: 1,
    area: 500,
    description:
      "A softly furnished studio with ash-wood joinery, linen drapes, and a calm neutral palette. Ash & Linen is a fully equipped furnished let ideal for a professional or postgraduate looking for a quiet, well-considered base.",
    details: {
      parking: 0,
      floors: 1,
      yearBuilt: 2020,
      furnished: true,
    },
  },
  {
    id: 69,
    name: "The Copper Penthouse",
    image: "/images/penthouse8.jpg",
    featured: false,
    type: "penthouse",
    saleType: "for sale",
    location: "Hillcrest Gardens",
    price: 2650000,
    bedrooms: 3,
    bathrooms: 3,
    area: 3600,
    description:
      "Named for its copper-clad roof terrace, this Hillcrest penthouse is a retreat above the city. The interiors are calming and refined — a neutral canvas interrupted by carefully selected art and handmade ceramic finishes.",
    details: {
      parking: 2,
      floors: 2,
      yearBuilt: 2019,
      furnished: false,
    },
  },
  {
    id: 70,
    name: "Saltbox House",
    image: "/images/house17.jpg",
    featured: false,
    type: "house",
    saleType: "for sale",
    location: "Old Harbor District",
    price: 1480000,
    bedrooms: 3,
    bathrooms: 2,
    area: 2300,
    description:
      "An iconic saltbox silhouette rendered in weathered cedar shingles at the edge of the harbor. Saltbox House is a distinctive property with three bedrooms, a roof deck, and a private mooring for a small vessel.",
    details: {
      parking: 1,
      floors: 2,
      yearBuilt: 1962,
      furnished: false,
    },
  },
  {
    id: 71,
    name: "Olive Branch Apartments",
    image: "/images/apartment26.jpg",
    featured: false,
    type: "apartment",
    saleType: "for sale",
    location: "Westside Quarter",
    price: 570000,
    bedrooms: 2,
    bathrooms: 1,
    area: 950,
    description:
      "A warm, well-run apartment block with a Mediterranean spirit and a central courtyard garden planted with olive trees. Olive Branch is a popular building with strong community feel and a low service charge.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 2010,
      furnished: false,
    },
  },
  {
    id: 72,
    name: "The Grand Crescent No. 5",
    image: "/images/apartment27.jpg",
    featured: false,
    type: "apartment",
    saleType: "for rent",
    location: "Uptown Heights",
    price: 5800,
    bedrooms: 3,
    bathrooms: 2,
    area: 1900,
    description:
      "A grand Regency apartment on the city's most iconic crescent. No. 5 has been restored to its full period splendour — ornate cornicing, marble fireplaces, and a double drawing room — while offering fully modernised kitchen and bathroom facilities.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 1820,
      furnished: false,
    },
  },
  {
    id: 73,
    name: "Prism Tower Suite 16",
    image: "/images/apartment28.jpg",
    featured: false,
    type: "apartment",
    saleType: "new dev",
    location: "Central Promenade",
    price: 1320000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1700,
    description:
      "A stunning three-bedroom suite in the recently completed Prism Tower, known for its faceted glass exterior that scatters light across the Promenade at dawn. The interior is sleek and modern with bespoke kitchen cabinetry and smart home integration.",
    details: {
      parking: 2,
      floors: 1,
      yearBuilt: 2025,
      furnished: false,
    },
  },
  {
    id: 74,
    name: "Creekside Studio",
    image: "/images/studio13.jpg",
    featured: false,
    type: "studio",
    saleType: "for rent",
    location: "Old Harbor District",
    price: 1650,
    bedrooms: 0,
    bathrooms: 1,
    area: 410,
    description:
      "A peaceful waterside studio on the quietest stretch of the old harbor creek. Creekside Studio has been recently refreshed with new flooring and appliances, and benefits from a private terrace right at water's edge.",
    details: {
      parking: 0,
      floors: 1,
      yearBuilt: 2007,
      furnished: true,
    },
  },
  {
    id: 75,
    name: "The Basalt",
    image: "/images/penthouse9.jpg",
    featured: false,
    type: "penthouse",
    saleType: "for sale",
    location: "Old Harbor District",
    price: 1850000,
    bedrooms: 2,
    bathrooms: 2,
    area: 2400,
    description:
      "A dark, dramatic penthouse with basalt stone floors and a raw concrete ceiling that gives it a distinctly artistic sensibility. The Basalt's harbour-facing terrace is one of the finest outdoor spaces in the district.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 2018,
      furnished: false,
    },
  },
  {
    id: 76,
    name: "Larkspur Lane House",
    image: "/images/house18.jpg",
    featured: false,
    type: "house",
    saleType: "for sale",
    location: "Hillcrest Gardens",
    price: 1560000,
    bedrooms: 4,
    bathrooms: 3,
    area: 3100,
    description:
      "A quietly beautiful family home on a sought-after Hillcrest lane. Larkspur is notable for its large rear garden, a kitchen garden with raised beds, and a studio workshop at the bottom of the plot.",
    details: {
      parking: 2,
      floors: 2,
      yearBuilt: 1973,
      furnished: false,
    },
  },
  {
    id: 77,
    name: "The Weave Apartment",
    image: "/images/apartment29.jpg",
    featured: false,
    type: "apartment",
    saleType: "for sale",
    location: "Riverside District",
    price: 660000,
    bedrooms: 1,
    bathrooms: 1,
    area: 880,
    description:
      "A textile-influenced apartment where woven wall panels, tactile fabrics, and layered textures replace the typical developer gloss. The Weave is a deeply personal and inviting space in a well-maintained riverside block.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 2015,
      furnished: false,
    },
  },
  {
    id: 78,
    name: "Duskline Villa",
    image: "/images/villa9.jpg",
    featured: false,
    type: "villa",
    saleType: "for sale",
    location: "Uptown Heights",
    price: 5800000,
    bedrooms: 7,
    bathrooms: 6,
    area: 8900,
    description:
      "A palatial Uptown villa designed to capture the city's famous dusk light across its west-facing facade. Seven bedroom suites, an indoor pool, a home theatre, and a rooftop observatory make Duskline one of the most complete private residences available.",
    details: {
      parking: 6,
      floors: 3,
      yearBuilt: 2013,
      furnished: false,
    },
  },
  {
    id: 79,
    name: "Foxhole Studio",
    image: "/images/studio14.jpg",
    featured: false,
    type: "studio",
    saleType: "for sale",
    location: "Westside Quarter",
    price: 295000,
    bedrooms: 0,
    bathrooms: 1,
    area: 385,
    description:
      "A snug, cleverly optimised studio that maximises every inch of its footprint. Foxhole is an excellent first property or buy-to-let investment in the heart of a neighborhood that continues to grow in popularity.",
    details: {
      parking: 0,
      floors: 1,
      yearBuilt: 2013,
      furnished: false,
    },
  },
  {
    id: 80,
    name: "Heather Hill House",
    image: "/images/house19.jpg",
    featured: false,
    type: "house",
    saleType: "for sale",
    location: "Hillcrest Gardens",
    price: 2250000,
    bedrooms: 5,
    bathrooms: 4,
    area: 4300,
    description:
      "Set at the highest point in Hillcrest Gardens, Heather Hill offers a commanding position with views stretching to the coastline on a clear day. A recently renovated interior and a landscaped garden with a wildflower meadow complete this exceptional home.",
    details: {
      parking: 3,
      floors: 3,
      yearBuilt: 1987,
      furnished: false,
    },
  },
  {
    id: 81,
    name: "Cobblestone Court No. 2",
    image: "/images/apartment30.jpg",
    featured: false,
    type: "apartment",
    saleType: "for rent",
    location: "Old Harbor District",
    price: 2750,
    bedrooms: 1,
    bathrooms: 1,
    area: 790,
    description:
      "A characterful first-floor apartment on one of the harbor's original cobblestone courts. Exposed stone walls, timber beams, and a wood-burning stove make Cobblestone Court No. 2 a truly atmospheric place to call home.",
    details: {
      parking: 0,
      floors: 1,
      yearBuilt: 1840,
      furnished: false,
    },
  },
  {
    id: 82,
    name: "The Topiary Penthouse",
    image: "/images/penthouse10.jpg",
    featured: false,
    type: "penthouse",
    saleType: "for rent",
    location: "Hillcrest Gardens",
    price: 12000,
    bedrooms: 4,
    bathrooms: 3,
    area: 4200,
    description:
      "A penthouse with a living room that opens directly onto a topiary garden — a half-acre of sculpted hedges and formal box parterres maintained by a dedicated gardener. Available on a minimum six-month tenancy.",
    details: {
      parking: 2,
      floors: 2,
      yearBuilt: 2016,
      furnished: true,
    },
  },
  {
    id: 83,
    name: "Moonshadow Apartments",
    image: "/images/apartment31.jpg",
    featured: false,
    type: "apartment",
    saleType: "for sale",
    location: "Central Promenade",
    price: 790000,
    bedrooms: 2,
    bathrooms: 1,
    area: 1080,
    description:
      "A well-designed two-bedroom apartment on the quieter south end of the Promenade. Moonshadow offers solid specification, a private parking space, and easy access to the Promenade's restaurants and cultural venues.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 2017,
      furnished: false,
    },
  },
  {
    id: 84,
    name: "Tidal House",
    image: "/images/house20.jpg",
    featured: false,
    type: "house",
    saleType: "for sale",
    location: "Old Harbor District",
    price: 2050000,
    bedrooms: 4,
    bathrooms: 3,
    area: 3600,
    description:
      "A striking contemporary house built directly above the tidal line with floor-to-ceiling glazing on the harbor elevation. Tidal House is a property of remarkable drama and intimacy with the sea — genuinely unlike anything else on the market.",
    details: {
      parking: 2,
      floors: 2,
      yearBuilt: 2020,
      furnished: false,
    },
  },
  {
    id: 85,
    name: "The Pearl Studio",
    image: "/images/studio15.jpg",
    featured: false,
    type: "studio",
    saleType: "for rent",
    location: "Central Promenade",
    price: 2950,
    bedrooms: 0,
    bathrooms: 1,
    area: 545,
    description:
      "A polished and luminous studio on the 15th floor of a Promenade landmark building. The Pearl Studio offers city and river views, premium furnishings, and access to a spa and infinity pool shared among residents.",
    details: {
      parking: 0,
      floors: 1,
      yearBuilt: 2022,
      furnished: true,
    },
  },
  {
    id: 86,
    name: "Bracken House",
    image: "/images/house21.jpg",
    featured: false,
    type: "house",
    saleType: "for sale",
    location: "Westside Quarter",
    price: 920000,
    bedrooms: 3,
    bathrooms: 2,
    area: 2050,
    description:
      "A well-loved semi-detached house in the leafier end of Westside. Bracken House has a large garden with a vegetable patch, a greenhouse, and a chicken run — an unusual urban smallholding with genuine family appeal.",
    details: {
      parking: 1,
      floors: 2,
      yearBuilt: 1968,
      furnished: false,
    },
  },
  {
    id: 87,
    name: "Cirrus Apartments No. 3",
    image: "/images/apartment32.jpg",
    featured: false,
    type: "apartment",
    saleType: "new dev",
    location: "Riverside District",
    price: 880000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1230,
    description:
      "Part of the cloud-inspired Cirrus development on the Riverside, No. 3 is a light-flooded corner apartment with balconies on two sides and a spec that includes underfloor heating, Miele appliances, and a Sonos sound system.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 2025,
      furnished: false,
    },
  },
  {
    id: 88,
    name: "Verdure Villa",
    image: "/images/villa10.jpg",
    featured: false,
    type: "villa",
    saleType: "for sale",
    location: "Hillcrest Gardens",
    price: 3200000,
    bedrooms: 5,
    bathrooms: 4,
    area: 5900,
    description:
      "A lush, garden-forward villa where the landscaping is as carefully considered as the architecture. Verdure's grounds include a kitchen garden, an orchard, a sunken rose garden, and a natural swimming pond.",
    details: {
      parking: 3,
      floors: 2,
      yearBuilt: 2009,
      furnished: false,
    },
  },
  {
    id: 89,
    name: "Ironside Studio",
    image: "/images/studio16.jpg",
    featured: false,
    type: "studio",
    saleType: "for sale",
    location: "Old Harbor District",
    price: 340000,
    bedrooms: 0,
    bathrooms: 1,
    area: 430,
    description:
      "A low-maintenance harbor-side studio with a direct water outlook and strong rental history. Ironside Studio is a practical and well-priced entry into one of the city's most historic and desirable neighborhoods.",
    details: {
      parking: 0,
      floors: 1,
      yearBuilt: 2011,
      furnished: false,
    },
  },
  {
    id: 90,
    name: "The Rookery",
    image: "/images/house22.jpg",
    featured: false,
    type: "house",
    saleType: "for sale",
    location: "Hillcrest Gardens",
    price: 3400000,
    bedrooms: 6,
    bathrooms: 5,
    area: 5600,
    description:
      "A majestic Arts and Crafts home on one of Hillcrest's finest private roads, set behind a colony of ancient rookery oaks that give the property its name. The interiors are rich with original period detail, updated thoughtfully over the years.",
    details: {
      parking: 4,
      floors: 3,
      yearBuilt: 1903,
      furnished: false,
    },
  },
  {
    id: 91,
    name: "Nimbus Apartments No. 6",
    image: "/images/apartment33.jpg",
    featured: false,
    type: "apartment",
    saleType: "for rent",
    location: "Uptown Heights",
    price: 3900,
    bedrooms: 2,
    bathrooms: 2,
    area: 1350,
    description:
      "A softly designed apartment in the Nimbus block, known for its excellent management and well-maintained communal spaces. No. 6 sits on the top residential floor with a private terrace and parkland views.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 2018,
      furnished: false,
    },
  },
  {
    id: 92,
    name: "Flint Row House",
    image: "/images/house23.jpg",
    featured: false,
    type: "house",
    saleType: "for sale",
    location: "Old Harbor District",
    price: 1290000,
    bedrooms: 3,
    bathrooms: 2,
    area: 2200,
    description:
      "A robust flint-fronted harbor row house with deep windowsills, a ship-lap cellar, and a rooftop crow's nest terrace. Flint Row is a home of genuine character and solidity, rarely found at this price in the district.",
    details: {
      parking: 0,
      floors: 3,
      yearBuilt: 1874,
      furnished: false,
    },
  },
  {
    id: 93,
    name: "The Opal Suite",
    image: "/images/apartment34.jpg",
    featured: false,
    type: "apartment",
    saleType: "for sale",
    location: "Hillcrest Gardens",
    price: 730000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1140,
    description:
      "A gently luminous apartment with opalescent wall finishes and wide-plank oak floors. The Opal Suite sits in a boutique building of just ten units, with a dedicated concierge and a communal kitchen garden.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 2021,
      furnished: false,
    },
  },
  {
    id: 94,
    name: "Harbour Reach Studio",
    image: "/images/studio17.jpg",
    featured: false,
    type: "studio",
    saleType: "for rent",
    location: "Riverside District",
    price: 2150,
    bedrooms: 0,
    bathrooms: 1,
    area: 490,
    description:
      "A neat, recently renovated studio at the reach of the river where it opens toward the harbor. Harbour Reach benefits from an unusual south-by-southwest orientation that fills it with light from midday to dusk.",
    details: {
      parking: 0,
      floors: 1,
      yearBuilt: 2014,
      furnished: true,
    },
  },
  {
    id: 95,
    name: "The Canopy",
    image: "/images/penthouse11.jpg",
    featured: false,
    type: "penthouse",
    saleType: "for sale",
    location: "Uptown Heights",
    price: 3700000,
    bedrooms: 4,
    bathrooms: 3,
    area: 4500,
    description:
      "A penthouse defined by its extraordinary planted rooftop canopy — over 200 species of plants cascading across a 1,500 sq ft living terrace. The Canopy is a genuine oasis above the city and one of the most unique residences in the country.",
    details: {
      parking: 2,
      floors: 2,
      yearBuilt: 2022,
      furnished: false,
    },
  },
  {
    id: 96,
    name: "Mulberry Street House",
    image: "/images/house24.jpg",
    featured: false,
    type: "house",
    saleType: "for sale",
    location: "Westside Quarter",
    price: 1450000,
    bedrooms: 4,
    bathrooms: 3,
    area: 2950,
    description:
      "A beautifully presented Victorian terrace on Westside's most celebrated residential street. Mulberry Street House retains much of its original character while offering a fully contemporary kitchen, loft conversion, and a rear courtyard garden.",
    details: {
      parking: 0,
      floors: 3,
      yearBuilt: 1886,
      furnished: false,
    },
  },
  {
    id: 97,
    name: "Equinox Apartments No. 11",
    image: "/images/apartment35.jpg",
    featured: false,
    type: "apartment",
    saleType: "new dev",
    location: "Uptown Heights",
    price: 990000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1320,
    description:
      "The penultimate unit in the sell-out Equinox development. No. 11 is dual-aspect with morning and evening sun, a large kitchen island, and a private terrace that looks over the Uptown skyline.",
    details: {
      parking: 1,
      floors: 1,
      yearBuilt: 2024,
      furnished: false,
    },
  },
  {
    id: 98,
    name: "Kelp House",
    image: "/images/house25.jpg",
    featured: false,
    type: "house",
    saleType: "for sale",
    location: "Old Harbor District",
    price: 1780000,
    bedrooms: 4,
    bathrooms: 3,
    area: 3300,
    description:
      "A striking harbor house with a dark stained timber facade that echoes the kelp beds visible at low tide. Kelp House was designed by a local architect to sit lightly on its waterfront site, with a passive solar layout and a wildflower green roof.",
    details: {
      parking: 2,
      floors: 2,
      yearBuilt: 2019,
      furnished: false,
    },
  },
  {
    id: 99,
    name: "The Onyx Studio",
    image: "/images/studio18.jpg",
    featured: false,
    type: "studio",
    saleType: "for sale",
    location: "Central Promenade",
    price: 415000,
    bedrooms: 0,
    bathrooms: 1,
    area: 520,
    description:
      "A sleek, all-black studio apartment for the buyer who wants something genuinely different. The Onyx features matte black cabinetry, onyx stone surfaces, and a concealed bed — a composed and highly considered micro-residence.",
    details: {
      parking: 0,
      floors: 1,
      yearBuilt: 2023,
      furnished: true,
    },
  },
  {
    id: 100,
    name: "The Solstice",
    image: "/images/villa11.jpg",
    featured: false,
    type: "villa",
    saleType: "for sale",
    location: "Hillcrest Gardens",
    price: 8500000,
    bedrooms: 9,
    bathrooms: 8,
    area: 12400,
    description:
      "The pinnacle of what Arca has to offer. The Solstice is a once-in-a-generation estate — over 12,000 square feet of architectural excellence set within six acres of landscaped grounds at the very crown of Hillcrest Gardens. A private helipad, a full spa complex, a 25-metre indoor pool, and a staff wing complete an offering that is simply without equal in this city.",
    details: {
      parking: 10,
      floors: 4,
      yearBuilt: 2015,
      furnished: false,
    },
  },
];
