import Navbar from "@/components/layout/Navbar";
import type { Metadata } from "next";
import { ProductProvider } from "../context/ProductContext";

export const metadata: Metadata = {
  title: {
    default: "Arca — Find Your Space",
    template: "%s | Arca",
  },
  description: "Generated by create next app",
};

export default function PagesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="">
      <Navbar />
      <div className="py-5 md:py-10">
        <ProductProvider>{children}</ProductProvider>
      </div>
    </div>
  );
}
